// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module floating_point_vecto (
        ap_clk,
        ap_rst,
        a_in_read,
        b_in_read,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] a_in_read;
input  [31:0] b_in_read;
output  [31:0] ap_return;
input   ap_ce;

wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage0;
wire   [31:0] grp_fu_28_p2;
reg    grp_fu_28_ce;

sdx_cppKernel_topbkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdx_cppKernel_topbkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_in_read),
    .din1(b_in_read),
    .ce(grp_fu_28_ce),
    .dout(grp_fu_28_p2)
);

always @ (*) begin
    if (((1'b1 == ap_ce) & (ap_block_pp0_stage0_11001 == 1'b0))) begin
        grp_fu_28_ce = 1'b1;
    end else begin
        grp_fu_28_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_return = grp_fu_28_p2;

endmodule //floating_point_vecto
