// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kernel_WRAPPER (
        ap_clk,
        ap_rst,
        a_in_V_read,
        b_in_V_read,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [511:0] a_in_V_read;
input  [511:0] b_in_V_read;
output  [511:0] ap_return;
input   ap_ce;

wire   [31:0] grp_floating_point_vecto_fu_94_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_94_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_94_ap_return;
reg    grp_floating_point_vecto_fu_94_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call7;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call7;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call7;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call7;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call7;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] grp_floating_point_vecto_fu_100_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_100_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_100_ap_return;
reg    grp_floating_point_vecto_fu_100_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_106_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_106_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_106_ap_return;
reg    grp_floating_point_vecto_fu_106_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_112_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_112_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_112_ap_return;
reg    grp_floating_point_vecto_fu_112_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_118_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_118_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_118_ap_return;
reg    grp_floating_point_vecto_fu_118_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_124_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_124_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_124_ap_return;
reg    grp_floating_point_vecto_fu_124_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_130_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_130_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_130_ap_return;
reg    grp_floating_point_vecto_fu_130_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_136_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_136_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_136_ap_return;
reg    grp_floating_point_vecto_fu_136_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_142_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_142_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_142_ap_return;
reg    grp_floating_point_vecto_fu_142_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_148_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_148_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_148_ap_return;
reg    grp_floating_point_vecto_fu_148_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_154_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_154_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_154_ap_return;
reg    grp_floating_point_vecto_fu_154_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_160_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_160_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_160_ap_return;
reg    grp_floating_point_vecto_fu_160_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_166_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_166_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_166_ap_return;
reg    grp_floating_point_vecto_fu_166_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_172_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_172_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_172_ap_return;
reg    grp_floating_point_vecto_fu_172_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_178_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_178_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_178_ap_return;
reg    grp_floating_point_vecto_fu_178_ap_ce;
wire   [31:0] grp_floating_point_vecto_fu_184_a_in_read;
wire   [31:0] grp_floating_point_vecto_fu_184_b_in_read;
wire   [31:0] grp_floating_point_vecto_fu_184_ap_return;
reg    grp_floating_point_vecto_fu_184_ap_ce;
wire    ap_block_pp0_stage0;
wire   [31:0] tmp_fu_190_p1;
wire   [31:0] tmp_5_fu_194_p1;
wire   [31:0] p_Result_s_fu_208_p4;
wire   [31:0] p_Result_1_1_fu_218_p4;
wire   [31:0] p_Result_2_fu_238_p4;
wire   [31:0] p_Result_1_2_fu_248_p4;
wire   [31:0] p_Result_3_fu_268_p4;
wire   [31:0] p_Result_1_3_fu_278_p4;
wire   [31:0] p_Result_4_fu_298_p4;
wire   [31:0] p_Result_1_4_fu_308_p4;
wire   [31:0] p_Result_5_fu_328_p4;
wire   [31:0] p_Result_1_5_fu_338_p4;
wire   [31:0] p_Result_6_fu_358_p4;
wire   [31:0] p_Result_1_6_fu_368_p4;
wire   [31:0] p_Result_7_fu_388_p4;
wire   [31:0] p_Result_1_7_fu_398_p4;
wire   [31:0] p_Result_8_fu_418_p4;
wire   [31:0] p_Result_1_8_fu_428_p4;
wire   [31:0] p_Result_9_fu_448_p4;
wire   [31:0] p_Result_1_9_fu_458_p4;
wire   [31:0] p_Result_1_fu_478_p4;
wire   [31:0] p_Result_1_s_fu_488_p4;
wire   [31:0] p_Result_10_fu_508_p4;
wire   [31:0] p_Result_1_10_fu_518_p4;
wire   [31:0] p_Result_11_fu_538_p4;
wire   [31:0] p_Result_1_11_fu_548_p4;
wire   [31:0] p_Result_12_fu_568_p4;
wire   [31:0] p_Result_1_12_fu_578_p4;
wire   [31:0] p_Result_13_fu_598_p4;
wire   [31:0] p_Result_1_13_fu_608_p4;
wire   [31:0] p_Result_14_fu_628_p4;
wire   [31:0] p_Result_1_14_fu_638_p4;
wire   [31:0] out_arg_0_14_fu_718_p1;
wire   [31:0] out_arg_0_13_fu_714_p1;
wire   [31:0] out_arg_0_12_fu_710_p1;
wire   [31:0] out_arg_0_11_fu_706_p1;
wire   [31:0] out_arg_0_10_fu_702_p1;
wire   [31:0] out_arg_0_s_fu_698_p1;
wire   [31:0] out_arg_0_9_fu_694_p1;
wire   [31:0] out_arg_0_8_fu_690_p1;
wire   [31:0] out_arg_0_7_fu_686_p1;
wire   [31:0] out_arg_0_6_fu_682_p1;
wire   [31:0] out_arg_0_5_fu_678_p1;
wire   [31:0] out_arg_0_4_fu_674_p1;
wire   [31:0] out_arg_0_3_fu_670_p1;
wire   [31:0] out_arg_0_2_fu_666_p1;
wire   [31:0] out_arg_0_1_fu_662_p1;
wire   [31:0] out_arg_0_fu_658_p1;

floating_point_vecto grp_floating_point_vecto_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_94_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_94_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_94_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_94_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_100(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_100_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_100_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_100_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_100_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_106_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_106_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_106_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_106_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_112(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_112_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_112_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_112_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_112_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_118(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_118_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_118_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_118_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_118_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_124(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_124_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_124_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_124_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_124_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_130_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_130_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_130_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_130_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_136(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_136_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_136_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_136_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_136_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_142_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_142_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_142_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_142_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_148(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_148_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_148_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_148_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_148_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_154(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_154_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_154_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_154_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_154_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_160_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_160_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_160_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_160_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_166(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_166_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_166_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_166_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_166_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_172(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_172_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_172_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_172_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_172_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_178(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_178_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_178_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_178_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_178_ap_ce)
);

floating_point_vecto grp_floating_point_vecto_fu_184(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .a_in_read(grp_floating_point_vecto_fu_184_a_in_read),
    .b_in_read(grp_floating_point_vecto_fu_184_b_in_read),
    .ap_return(grp_floating_point_vecto_fu_184_ap_return),
    .ap_ce(grp_floating_point_vecto_fu_184_ap_ce)
);

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_100_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_100_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_106_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_106_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_112_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_112_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_118_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_118_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_124_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_124_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_130_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_130_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_136_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_136_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_142_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_142_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_148_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_148_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_154_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_154_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_160_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_160_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_166_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_166_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_172_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_172_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_178_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_178_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_184_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_184_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_ce))) begin
        grp_floating_point_vecto_fu_94_ap_ce = 1'b1;
    end else begin
        grp_floating_point_vecto_fu_94_ap_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call7 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call7 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call7 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call7 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call7 = ~(1'b1 == 1'b1);

assign ap_return = {{{{{{{{{{{{{{{{out_arg_0_14_fu_718_p1}, {out_arg_0_13_fu_714_p1}}, {out_arg_0_12_fu_710_p1}}, {out_arg_0_11_fu_706_p1}}, {out_arg_0_10_fu_702_p1}}, {out_arg_0_s_fu_698_p1}}, {out_arg_0_9_fu_694_p1}}, {out_arg_0_8_fu_690_p1}}, {out_arg_0_7_fu_686_p1}}, {out_arg_0_6_fu_682_p1}}, {out_arg_0_5_fu_678_p1}}, {out_arg_0_4_fu_674_p1}}, {out_arg_0_3_fu_670_p1}}, {out_arg_0_2_fu_666_p1}}, {out_arg_0_1_fu_662_p1}}, {out_arg_0_fu_658_p1}};

assign grp_floating_point_vecto_fu_100_a_in_read = p_Result_s_fu_208_p4;

assign grp_floating_point_vecto_fu_100_b_in_read = p_Result_1_1_fu_218_p4;

assign grp_floating_point_vecto_fu_106_a_in_read = p_Result_2_fu_238_p4;

assign grp_floating_point_vecto_fu_106_b_in_read = p_Result_1_2_fu_248_p4;

assign grp_floating_point_vecto_fu_112_a_in_read = p_Result_3_fu_268_p4;

assign grp_floating_point_vecto_fu_112_b_in_read = p_Result_1_3_fu_278_p4;

assign grp_floating_point_vecto_fu_118_a_in_read = p_Result_4_fu_298_p4;

assign grp_floating_point_vecto_fu_118_b_in_read = p_Result_1_4_fu_308_p4;

assign grp_floating_point_vecto_fu_124_a_in_read = p_Result_5_fu_328_p4;

assign grp_floating_point_vecto_fu_124_b_in_read = p_Result_1_5_fu_338_p4;

assign grp_floating_point_vecto_fu_130_a_in_read = p_Result_6_fu_358_p4;

assign grp_floating_point_vecto_fu_130_b_in_read = p_Result_1_6_fu_368_p4;

assign grp_floating_point_vecto_fu_136_a_in_read = p_Result_7_fu_388_p4;

assign grp_floating_point_vecto_fu_136_b_in_read = p_Result_1_7_fu_398_p4;

assign grp_floating_point_vecto_fu_142_a_in_read = p_Result_8_fu_418_p4;

assign grp_floating_point_vecto_fu_142_b_in_read = p_Result_1_8_fu_428_p4;

assign grp_floating_point_vecto_fu_148_a_in_read = p_Result_9_fu_448_p4;

assign grp_floating_point_vecto_fu_148_b_in_read = p_Result_1_9_fu_458_p4;

assign grp_floating_point_vecto_fu_154_a_in_read = p_Result_1_fu_478_p4;

assign grp_floating_point_vecto_fu_154_b_in_read = p_Result_1_s_fu_488_p4;

assign grp_floating_point_vecto_fu_160_a_in_read = p_Result_10_fu_508_p4;

assign grp_floating_point_vecto_fu_160_b_in_read = p_Result_1_10_fu_518_p4;

assign grp_floating_point_vecto_fu_166_a_in_read = p_Result_11_fu_538_p4;

assign grp_floating_point_vecto_fu_166_b_in_read = p_Result_1_11_fu_548_p4;

assign grp_floating_point_vecto_fu_172_a_in_read = p_Result_12_fu_568_p4;

assign grp_floating_point_vecto_fu_172_b_in_read = p_Result_1_12_fu_578_p4;

assign grp_floating_point_vecto_fu_178_a_in_read = p_Result_13_fu_598_p4;

assign grp_floating_point_vecto_fu_178_b_in_read = p_Result_1_13_fu_608_p4;

assign grp_floating_point_vecto_fu_184_a_in_read = p_Result_14_fu_628_p4;

assign grp_floating_point_vecto_fu_184_b_in_read = p_Result_1_14_fu_638_p4;

assign grp_floating_point_vecto_fu_94_a_in_read = tmp_fu_190_p1;

assign grp_floating_point_vecto_fu_94_b_in_read = tmp_5_fu_194_p1;

assign out_arg_0_10_fu_702_p1 = grp_floating_point_vecto_fu_160_ap_return;

assign out_arg_0_11_fu_706_p1 = grp_floating_point_vecto_fu_166_ap_return;

assign out_arg_0_12_fu_710_p1 = grp_floating_point_vecto_fu_172_ap_return;

assign out_arg_0_13_fu_714_p1 = grp_floating_point_vecto_fu_178_ap_return;

assign out_arg_0_14_fu_718_p1 = grp_floating_point_vecto_fu_184_ap_return;

assign out_arg_0_1_fu_662_p1 = grp_floating_point_vecto_fu_100_ap_return;

assign out_arg_0_2_fu_666_p1 = grp_floating_point_vecto_fu_106_ap_return;

assign out_arg_0_3_fu_670_p1 = grp_floating_point_vecto_fu_112_ap_return;

assign out_arg_0_4_fu_674_p1 = grp_floating_point_vecto_fu_118_ap_return;

assign out_arg_0_5_fu_678_p1 = grp_floating_point_vecto_fu_124_ap_return;

assign out_arg_0_6_fu_682_p1 = grp_floating_point_vecto_fu_130_ap_return;

assign out_arg_0_7_fu_686_p1 = grp_floating_point_vecto_fu_136_ap_return;

assign out_arg_0_8_fu_690_p1 = grp_floating_point_vecto_fu_142_ap_return;

assign out_arg_0_9_fu_694_p1 = grp_floating_point_vecto_fu_148_ap_return;

assign out_arg_0_fu_658_p1 = grp_floating_point_vecto_fu_94_ap_return;

assign out_arg_0_s_fu_698_p1 = grp_floating_point_vecto_fu_154_ap_return;

assign p_Result_10_fu_508_p4 = {{a_in_V_read[383:352]}};

assign p_Result_11_fu_538_p4 = {{a_in_V_read[415:384]}};

assign p_Result_12_fu_568_p4 = {{a_in_V_read[447:416]}};

assign p_Result_13_fu_598_p4 = {{a_in_V_read[479:448]}};

assign p_Result_14_fu_628_p4 = {{a_in_V_read[511:480]}};

assign p_Result_1_10_fu_518_p4 = {{b_in_V_read[383:352]}};

assign p_Result_1_11_fu_548_p4 = {{b_in_V_read[415:384]}};

assign p_Result_1_12_fu_578_p4 = {{b_in_V_read[447:416]}};

assign p_Result_1_13_fu_608_p4 = {{b_in_V_read[479:448]}};

assign p_Result_1_14_fu_638_p4 = {{b_in_V_read[511:480]}};

assign p_Result_1_1_fu_218_p4 = {{b_in_V_read[63:32]}};

assign p_Result_1_2_fu_248_p4 = {{b_in_V_read[95:64]}};

assign p_Result_1_3_fu_278_p4 = {{b_in_V_read[127:96]}};

assign p_Result_1_4_fu_308_p4 = {{b_in_V_read[159:128]}};

assign p_Result_1_5_fu_338_p4 = {{b_in_V_read[191:160]}};

assign p_Result_1_6_fu_368_p4 = {{b_in_V_read[223:192]}};

assign p_Result_1_7_fu_398_p4 = {{b_in_V_read[255:224]}};

assign p_Result_1_8_fu_428_p4 = {{b_in_V_read[287:256]}};

assign p_Result_1_9_fu_458_p4 = {{b_in_V_read[319:288]}};

assign p_Result_1_fu_478_p4 = {{a_in_V_read[351:320]}};

assign p_Result_1_s_fu_488_p4 = {{b_in_V_read[351:320]}};

assign p_Result_2_fu_238_p4 = {{a_in_V_read[95:64]}};

assign p_Result_3_fu_268_p4 = {{a_in_V_read[127:96]}};

assign p_Result_4_fu_298_p4 = {{a_in_V_read[159:128]}};

assign p_Result_5_fu_328_p4 = {{a_in_V_read[191:160]}};

assign p_Result_6_fu_358_p4 = {{a_in_V_read[223:192]}};

assign p_Result_7_fu_388_p4 = {{a_in_V_read[255:224]}};

assign p_Result_8_fu_418_p4 = {{a_in_V_read[287:256]}};

assign p_Result_9_fu_448_p4 = {{a_in_V_read[319:288]}};

assign p_Result_s_fu_208_p4 = {{a_in_V_read[63:32]}};

assign tmp_5_fu_194_p1 = b_in_V_read[31:0];

assign tmp_fu_190_p1 = a_in_V_read[31:0];

endmodule //kernel_WRAPPER
