# Created : 16:59:35, Fri May 20, 2016 : Sanjay Rai

.PHONY: all

all: build_all

build_all:
	#g++ -g3 -std=c++0x pcie_memio.cpp -o pcie_memio
	g++ -std=c++0x pcie_memio.cpp -o pcie_memio
clean:
	rm pcie_memio

