create_clock -name sys_clk -period 10 [get_ports sys_clk_p]

set_false_path -from [get_ports sys_rst_n]

set_property LOC [get_package_pins -filter {PIN_FUNC == IO_T3U_N12_PERSTN0_65}] [get_ports sys_rst_n]
set_property PULLUP true [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS12 [get_ports sys_rst_n]


##### REFCLK_IBUF###########
#set_property LOC AB6 [get_cells refclk_ibuf]
set_property LOC AT11  [get_ports sys_clk_p]
set_property LOC AT10  [get_ports sys_clk_n]

set_property LOC AP2   [get_ports pcie_mgt_rxp[0]]
set_property LOC AR4   [get_ports pcie_mgt_rxp[1]]
set_property LOC AT2   [get_ports pcie_mgt_rxp[2]]
set_property LOC AU4   [get_ports pcie_mgt_rxp[3]]
set_property LOC AV2   [get_ports pcie_mgt_rxp[4]]
set_property LOC AW4   [get_ports pcie_mgt_rxp[5]]
set_property LOC BA2   [get_ports pcie_mgt_rxp[6]]
set_property LOC BC2   [get_ports pcie_mgt_rxp[7]]
set_property LOC AF2   [get_ports pcie_mgt_rxp[8]]
set_property LOC AG4   [get_ports pcie_mgt_rxp[9]]
set_property LOC AH2   [get_ports pcie_mgt_rxp[10]]
set_property LOC AJ4   [get_ports pcie_mgt_rxp[11]]
set_property LOC AK2   [get_ports pcie_mgt_rxp[12]]
set_property LOC AL4   [get_ports pcie_mgt_rxp[13]]
set_property LOC AM2   [get_ports pcie_mgt_rxp[14]]
set_property LOC AN4   [get_ports pcie_mgt_rxp[15]]


set_property LOC AP7   [get_ports pcie_mgt_txp[0]]
set_property LOC AR9   [get_ports pcie_mgt_txp[1]]
set_property LOC AT7   [get_ports pcie_mgt_txp[2]]
set_property LOC AU9   [get_ports pcie_mgt_txp[3]]
set_property LOC AV7   [get_ports pcie_mgt_txp[4]]
set_property LOC BB5   [get_ports pcie_mgt_txp[5]]
set_property LOC BD5   [get_ports pcie_mgt_txp[6]]
set_property LOC BF5   [get_ports pcie_mgt_txp[7]]
set_property LOC AF7   [get_ports pcie_mgt_txp[8]]
set_property LOC AG9   [get_ports pcie_mgt_txp[9]]
set_property LOC AH7   [get_ports pcie_mgt_txp[10]]
set_property LOC AJ9   [get_ports pcie_mgt_txp[11]]
set_property LOC AK7   [get_ports pcie_mgt_txp[12]]
set_property LOC AL9   [get_ports pcie_mgt_txp[13]]
set_property LOC AM7   [get_ports pcie_mgt_txp[14]]
set_property LOC AN9   [get_ports pcie_mgt_txp[15]]

create_pblock pblock_U_HLS_PR_module
add_cells_to_pblock [get_pblocks pblock_U_HLS_PR_module] [get_cells HLS_PR_0_i]
resize_pblock [get_pblocks pblock_U_HLS_PR_module] -add {CLOCKREGION_X0Y10:CLOCKREGION_X5Y14}
set_property HD.RECONFIGURABLE true [get_cells HLS_PR_0_i]


# Configuration
# ------------------------------------------------------------------------------
set_property CONFIG_VOLTAGE 1.8                      [current_design]
set_property BITSTREAM.CONFIG.CONFIGFALLBACK Enable  [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE         [current_design]
set_property CONFIG_MODE SPIx8                       [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 8         [current_design]
set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN div-1 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES      [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup       [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR Yes     [current_design]



#DDR4_ C0 controller:
set_property PACKAGE_PIN AW14       [get_ports c0_sys_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports c0_sys_clk_p]
set_property PACKAGE_PIN AW13       [get_ports c0_sys_clk_n]
set_property IOSTANDARD DIFF_SSTL12 [get_ports c0_sys_clk_n]

set_property PACKAGE_PIN AV13       [get_ports c0_ddr4_act_n]
set_property PACKAGE_PIN AM14       [get_ports {c0_ddr4_adr[0]}]
set_property PACKAGE_PIN AM15       [get_ports {c0_ddr4_adr[10]}]
set_property PACKAGE_PIN AR13       [get_ports {c0_ddr4_adr[11]}]
set_property PACKAGE_PIN AR16       [get_ports {c0_ddr4_adr[12]}]
set_property PACKAGE_PIN AN13       [get_ports {c0_ddr4_adr[13]}]
set_property PACKAGE_PIN AL14       [get_ports {c0_ddr4_adr[14]}]
set_property PACKAGE_PIN AN14       [get_ports {c0_ddr4_adr[15]}]
set_property PACKAGE_PIN AP13       [get_ports {c0_ddr4_adr[16]}]
set_property PACKAGE_PIN AV16       [get_ports {c0_ddr4_adr[1]}]
set_property PACKAGE_PIN AT13       [get_ports {c0_ddr4_adr[2]}]
set_property PACKAGE_PIN AP14       [get_ports {c0_ddr4_adr[3]}]
set_property PACKAGE_PIN AU16       [get_ports {c0_ddr4_adr[4]}]
set_property PACKAGE_PIN AU15       [get_ports {c0_ddr4_adr[5]}]
set_property PACKAGE_PIN AT15       [get_ports {c0_ddr4_adr[6]}]
set_property PACKAGE_PIN AR15       [get_ports {c0_ddr4_adr[7]}]
set_property PACKAGE_PIN AL15       [get_ports {c0_ddr4_adr[8]}]
set_property PACKAGE_PIN AP15       [get_ports {c0_ddr4_adr[9]}]
set_property PACKAGE_PIN AW16       [get_ports {c0_ddr4_ba[0]}]
set_property PACKAGE_PIN AW15       [get_ports {c0_ddr4_ba[1]}]
set_property PACKAGE_PIN AU13       [get_ports {c0_ddr4_bg[0]}]
set_property PACKAGE_PIN AU14       [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN AV14       [get_ports {c0_ddr4_ck_c[0]}]
set_property PACKAGE_PIN BB16       [get_ports {c0_ddr4_cke[0]}]
set_property PACKAGE_PIN BF13       [get_ports {c0_ddr4_cs_n[0]}]
set_property PACKAGE_PIN BE17       [get_ports {c0_ddr4_dm_n[0]}]
set_property PACKAGE_PIN AY17       [get_ports {c0_ddr4_dm_n[1]}]
set_property PACKAGE_PIN AT19       [get_ports {c0_ddr4_dm_n[2]}]
set_property PACKAGE_PIN AN18       [get_ports {c0_ddr4_dm_n[3]}]
set_property PACKAGE_PIN BF14       [get_ports {c0_ddr4_dm_n[4]}]
set_property PACKAGE_PIN BA12       [get_ports {c0_ddr4_dm_n[5]}]
set_property PACKAGE_PIN BE7        [get_ports {c0_ddr4_dm_n[6]}]
set_property PACKAGE_PIN BC12       [get_ports {c0_ddr4_dm_n[7]}]
set_property PACKAGE_PIN BF18       [get_ports {c0_ddr4_dq[0]}]
set_property PACKAGE_PIN AW20       [get_ports {c0_ddr4_dq[10]}]
set_property PACKAGE_PIN AV18       [get_ports {c0_ddr4_dq[11]}]
set_property PACKAGE_PIN AW18       [get_ports {c0_ddr4_dq[12]}]
set_property PACKAGE_PIN BA18       [get_ports {c0_ddr4_dq[13]}]
set_property PACKAGE_PIN AV19       [get_ports {c0_ddr4_dq[14]}]
set_property PACKAGE_PIN AY18       [get_ports {c0_ddr4_dq[15]}]
set_property PACKAGE_PIN AP18       [get_ports {c0_ddr4_dq[16]}]
set_property PACKAGE_PIN AR20       [get_ports {c0_ddr4_dq[17]}]
set_property PACKAGE_PIN AT20       [get_ports {c0_ddr4_dq[18]}]
set_property PACKAGE_PIN AT18       [get_ports {c0_ddr4_dq[19]}]
set_property PACKAGE_PIN BE18       [get_ports {c0_ddr4_dq[1]}]
set_property PACKAGE_PIN AP20       [get_ports {c0_ddr4_dq[20]}]
set_property PACKAGE_PIN AR18       [get_ports {c0_ddr4_dq[21]}]
set_property PACKAGE_PIN AU20       [get_ports {c0_ddr4_dq[22]}]
set_property PACKAGE_PIN AU17       [get_ports {c0_ddr4_dq[23]}]
set_property PACKAGE_PIN AM16       [get_ports {c0_ddr4_dq[24]}]
set_property PACKAGE_PIN AP19       [get_ports {c0_ddr4_dq[25]}]
set_property PACKAGE_PIN AN16       [get_ports {c0_ddr4_dq[26]}]
set_property PACKAGE_PIN AN19       [get_ports {c0_ddr4_dq[27]}]
set_property PACKAGE_PIN AM19       [get_ports {c0_ddr4_dq[28]}]
set_property PACKAGE_PIN AL20       [get_ports {c0_ddr4_dq[29]}]
set_property PACKAGE_PIN BF19       [get_ports {c0_ddr4_dq[2]}]
set_property PACKAGE_PIN AL19       [get_ports {c0_ddr4_dq[30]}]
set_property PACKAGE_PIN AM20       [get_ports {c0_ddr4_dq[31]}]
set_property PACKAGE_PIN BF15       [get_ports {c0_ddr4_dq[32]}]
set_property PACKAGE_PIN BC14       [get_ports {c0_ddr4_dq[33]}]
set_property PACKAGE_PIN BD16       [get_ports {c0_ddr4_dq[34]}]
set_property PACKAGE_PIN BD14       [get_ports {c0_ddr4_dq[35]}]
set_property PACKAGE_PIN BE15       [get_ports {c0_ddr4_dq[36]}]
set_property PACKAGE_PIN BD15       [get_ports {c0_ddr4_dq[37]}]
set_property PACKAGE_PIN BC13       [get_ports {c0_ddr4_dq[38]}]
set_property PACKAGE_PIN BE16       [get_ports {c0_ddr4_dq[39]}]
set_property PACKAGE_PIN BC17       [get_ports {c0_ddr4_dq[3]}]
set_property PACKAGE_PIN AY12       [get_ports {c0_ddr4_dq[40]}]
set_property PACKAGE_PIN AY11       [get_ports {c0_ddr4_dq[41]}]
set_property PACKAGE_PIN BA13       [get_ports {c0_ddr4_dq[42]}]
set_property PACKAGE_PIN AY15       [get_ports {c0_ddr4_dq[43]}]
set_property PACKAGE_PIN BA15       [get_ports {c0_ddr4_dq[44]}]
set_property PACKAGE_PIN BA14       [get_ports {c0_ddr4_dq[45]}]
set_property PACKAGE_PIN AY16       [get_ports {c0_ddr4_dq[46]}]
set_property PACKAGE_PIN AY13       [get_ports {c0_ddr4_dq[47]}]
set_property PACKAGE_PIN BE12       [get_ports {c0_ddr4_dq[48]}]
set_property PACKAGE_PIN BF9        [get_ports {c0_ddr4_dq[49]}]
set_property PACKAGE_PIN BC18       [get_ports {c0_ddr4_dq[4]}]
set_property PACKAGE_PIN BD8        [get_ports {c0_ddr4_dq[50]}]
set_property PACKAGE_PIN BD9        [get_ports {c0_ddr4_dq[51]}]
set_property PACKAGE_PIN BF12       [get_ports {c0_ddr4_dq[52]}]
set_property PACKAGE_PIN BF10       [get_ports {c0_ddr4_dq[53]}]
set_property PACKAGE_PIN BE8        [get_ports {c0_ddr4_dq[54]}]
set_property PACKAGE_PIN BF8        [get_ports {c0_ddr4_dq[55]}]
set_property PACKAGE_PIN BA9        [get_ports {c0_ddr4_dq[56]}]
set_property PACKAGE_PIN BB9        [get_ports {c0_ddr4_dq[57]}]
set_property PACKAGE_PIN BC9        [get_ports {c0_ddr4_dq[58]}]
set_property PACKAGE_PIN BB11       [get_ports {c0_ddr4_dq[59]}]
set_property PACKAGE_PIN BB17       [get_ports {c0_ddr4_dq[5]}]
set_property PACKAGE_PIN BC8        [get_ports {c0_ddr4_dq[60]}]
set_property PACKAGE_PIN BC7        [get_ports {c0_ddr4_dq[61]}]
set_property PACKAGE_PIN BB10       [get_ports {c0_ddr4_dq[62]}]
set_property PACKAGE_PIN BA8        [get_ports {c0_ddr4_dq[63]}]
set_property PACKAGE_PIN BD18       [get_ports {c0_ddr4_dq[6]}]
set_property PACKAGE_PIN BB19       [get_ports {c0_ddr4_dq[7]}]
set_property PACKAGE_PIN AY20       [get_ports {c0_ddr4_dq[8]}]
set_property PACKAGE_PIN AW19       [get_ports {c0_ddr4_dq[9]}]
set_property PACKAGE_PIN BC19       [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN BD19       [get_ports {c0_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN AV21       [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN AW21       [get_ports {c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN AR17       [get_ports {c0_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN AT17       [get_ports {c0_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN AL17       [get_ports {c0_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN AM17       [get_ports {c0_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN BD13       [get_ports {c0_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN BE13       [get_ports {c0_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN BB15       [get_ports {c0_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN BB14       [get_ports {c0_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN BE11       [get_ports {c0_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN BE10       [get_ports {c0_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN BA7        [get_ports {c0_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN BB7        [get_ports {c0_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN BB12       [get_ports {c0_ddr4_odt[0]}]
set_property PACKAGE_PIN AU19       [get_ports c0_ddr4_reset_n]

